### ISSUE TITLE
slippy-netplay does not have xdg-open

### ISSUE THREAD

**Issue by floyza** [djanatyn/ssbm-nix#19]
It appears that `slippy-netplay` gets its `xdg-open` from the user environment. Without `xdg_utils` in my environment I get `sh: line 1: xdg-open: command not found`.

**Comment by floyza** [comment]
The initial login requires `xdg-open`, but I'm not sure if anything else does.

**Comment by djanatyn** [comment]
I just added `xdg_utils` to dependencies in `slippi/default.nix` here:
* https://github.com/djanatyn/ssbm-nix/commit/4704db441a398ba23fc1f9cc7e27471a53798d7e

I'm building a new version to test.

```
sh: line 1: xdg-open: command not found
```

I usually have `xdg-open` in my environment, so I haven't seen this - I'll try to reproduce.

**Comment by floyza** [comment]
Yeah, you already have xdg_utils in buildInputs, it looks like.

**Comment by djanatyn** [comment]
Oh sorry, didn't understand at first (and didn't notice we were already using it to build).

Hmm, can we modify our derivation to provide the `xdg_utils` package from `buildInputs` whenever we're running `slippi-netplay`? Not sure what the appropriate convention would be here, reading some docs.

In the meantime, thanks for logging this issue!
