### ISSUE TITLE
slippi-netplay non-portable build?

### ISSUE THREAD

**Issue by critbase** [djanatyn/ssbm-nix#4]
while i was looking through the expression (for #3), i noticed this line in the postBuild phase: `touch Binaries/portable.txt`. i haven't tested this yet, but i believe removing this makes the dolphin build non-portable, and also would allow us to get rid of `----add-flags '-u $HOME/.config/slippi-playback'` in the wrapper, as it should default to `~/.config/SlippiOnline` if i'm not wrong.
i'll test this later today or tomorrow, and maybe make a pull request if things look good, unless there's a reason for packaging dolphin the way it is now.

**Comment by critbase** [comment]
well, i tested it real quick and it works as expected. making slippi-netplay nonportable just defaults to using ~/.config/SlippiOnline.

**Comment by 6AA4FD** [comment]
fixed in #3
